<div>{{JSRef}}</div>

<p><span class="seoSummary"><strong><code>Error</code></strong> コンストラクターは、エラーオブジェクトを生成します。</span> <code>Error</code> オブジェクトのインスタンスは、ランタイムエラーが発生した時に投げられます。<code>Error</code> オブジェクトは、ユーザー定義の例外の基底オブジェクトとして使用することもできます。標準の組み込みエラー型については下記を参照してください。</p>

<h2 id="Syntax" name="Syntax">構文</h2>

<pre class="syntaxbox">new Error([<var>message</var>[, <var>fileName</var>[, <var>lineNumber</var>]]])</pre>

<h3 id="Parameters" name="Parameters">引数</h3>

<dl>
 <dt><code><var>message</var></code></dt>
 <dd>人間が読めるエラーの説明。</dd>
 <dt><code><var>fileName</var></code> {{optional_inline}} {{non-standard_inline}}</dt>
 <dd>生成された <code>Error</code> オブジェクト上の <code><var>fileName</var></code> プロパティに設定される値。デフォルトでは、<code>Error()</code> コンストラクターを呼び出したコードを含むファイルの名前。</dd>
 <dt><code><var>lineNumber</var></code> {{optional_inline}} {{non-standard_inline}}</dt>
 <dd>生成された <code>Error</code> オブジェクト上の <code><var>lineNumber</var></code> プロパティに設定される値。デフォルトでは、<code>Error()</code> コンストラクターの呼び出しを含む行番号。</dd>
</dl>

<h2 id="Description" name="Description">説明</h2>

<p>ランタイムエラーが発生すると、新しい <code>Error</code> オブジェクトが生成され、投げられます。</p>

<p>このページは、<code>Error</code> オブジェクト自体の使い方と、それをコンストラクター関数として使うことについて書かれています。<code>Error</code> インスタンスに継承されるプロパティとメソッドのリストについては、{{jsxref("Error.prototype")}} を参照してください。</p>

<h3 id="Used_as_a_function" name="Used_as_a_function">関数として使う</h3>

<p><code>Error</code> が {{jsxref("Operators/new", "new")}} 演算子を用いずに、通常の関数として使用された場合、<code>Error</code> オブジェクトを返します。よって、単に <code>Error</code> を呼び出した場合も、<code>new</code> 演算子を使用した場合と同等の挙動となります。</p>

<pre class="brush: js">// this:
const x = Error('I was created using a function call!');
​​​​// has the same functionality as this:
const y = new Error('I was constructed via the "new" keyword!');
</pre>

<h3 id="Error_types" name="Error_types">エラーの型</h3>

<p>JavaScript には、一般的な <code>Error</code> コンストラクタの他に、中核となる 7 つのエラーコンストラクターがあります。クライアント側の例外については、<a href="/ja/docs/Web/JavaScript/Guide/Statements#Exception_Handling_Statements">Exception Handling Statements</a> を参照してください。</p>

<dl>
 <dt>{{jsxref("EvalError")}}</dt>
 <dd>グローバル関数 {{jsxref("eval", "eval()")}} に関して発生するエラーを表すインスタンスを生成します。</dd>
 <dt>{{jsxref("InternalError")}} {{non-standard_inline}}</dt>
 <dd>"too much recursion" (過剰な再帰) など、JavaScript エンジンで内部エラーが投げられた時に発生するエラーを表すインスタンスを生成します。</dd>
 <dt>{{jsxref("RangeError")}}</dt>
 <dd>数値変数または引数が、その有効範囲外である場合に発生するエラーを表すインスタンスを生成します。</dd>
 <dt>{{jsxref("ReferenceError")}}</dt>
 <dd>不正な参照から参照先の値を取得した時に発生するエラーを表すインスタンスを生成します。</dd>
 <dt>{{jsxref("SyntaxError")}}</dt>
 <dd>{{jsxref("eval", "eval()")}} 内のコードの解釈中に発生する構文エラーを表すインスタンスを生成します。</dd>
 <dt>{{jsxref("TypeError")}}</dt>
 <dd>変数または引数の型が有効でない場合に発生するエラーを表すインスタンスを生成します。</dd>
 <dt>{{jsxref("URIError")}}</dt>
 <dd>{{jsxref("encodeURI", "encodeURI()")}} または {{jsxref("decodeURI", "decodeURI()")}} に不正な引数が渡された時に発生するエラーを表すインスタンスを生成します。</dd>
</dl>

<h2 id="Properties" name="Properties">プロパティ</h2>

<dl>
 <dt>{{jsxref("Error.prototype")}}</dt>
 <dd><code>Error</code> インスタンスにプロパティを追加できます。</dd>
</dl>

<h2 id="Methods" name="Methods">メソッド</h2>

<p>グローバルな <code>Error</code> オブジェクトは、自分自身のメソッドを持っていませんが、プロトタイプチェーンを通していくつかのメソッドを継承しています。</p>

<h2 id="Error_instances" name="Error_instances"><code>Error</code> インスタンス</h2>

<div>{{page('ja/docs/Web/JavaScript/Reference/Global_Objects/Error/prototype','Description')}}</div>

<h3 id="Properties" name="Properties">プロパティ</h3>

<div>{{page('ja/docs/Web/JavaScript/Reference/Global_Objects/Error/prototype','Properties')}}</div>

<h3 id="Methods" name="Methods">メソッド</h3>

<div>{{page('ja/docs/Web/JavaScript/Reference/Global_Objects/Error/prototype','Methods')}}</div>

<h2 id="Examples" name="Examples">例</h2>

<h3 id="Throwing_a_generic_error" name="Throwing_a_generic_error">一般的なエラーを投げる</h3>

<p>通常、{{jsxref("Statements/throw", "throw")}} キーワードを使い意図的にエラーを発生させて <code>Error</code> オブジェクトを生成します。{{jsxref("Statements/try...catch", "try...catch")}} 構文を使用してエラーを処理してください:</p>

<pre class="brush: js">try {
  throw new Error('Whoops!');
} catch (e) {
  console.error(e.name + ': ' + e.message);
}
</pre>

<h3 id="Handling_a_specific_error" name="Handling_a_specific_error">特定のエラーを処理する</h3>

<p>エラーの {{jsxref("Object.prototype.constructor", "constructor")}} プロパティでエラー型をテストすることにより、特定のエラー型だけを選んで処理できます。または、最近の JavaScript エンジン向けに書いているのであれば、{{jsxref("Operators/instanceof", "instanceof")}} キーワードが使えます:</p>

<pre class="brush: js">try {
  foo.bar();
} catch (e) {
  if (e instanceof EvalError) {
    console.error(e.name + ': ' + e.message);
  } else if (e instanceof RangeError) {
    console.error(e.name + ': ' + e.message);
  }
  // ... etc
}
</pre>

<h3 id="Custom_Error_Types" name="Custom_Error_Types">独自のエラー型</h3>

<p><code>Error</code> から派生した独自のエラー型を定義して <code>throw new CustomError()</code> ができるようにし、<code>instanceof CustomError</code> で例外ハンドラー内のエラーの種類を確認したいでしょう。これを行う一般的な方法の実例を以下に示します。StackOverflow の突っ込んだ議論、<a href="http://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript">"What's a good way to extend Error in JavaScript?"</a> も参照してください。</p>

<h4 id="ES6_Custom_Error_Class" name="ES6_Custom_Error_Class">ES6 独自のエラークラス</h4>

<div class="warning">
<p>Babel 7 以降では独自のエラークラスのメソッドを使用することができますが、<a href="https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty">Object.defineProperty()</a> で宣言された場合に限定されます。そうでない場合、古い Babel やそれ以外のトランスパイラは、下記のコードを正しく処理するために<a href="https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend">追加の設定</a>を必要とします。</p>
</div>

<div class="note">
<p>ES2015 クラスを使用した場合、一部のブラウザーのスタックトレース上に、CustomError コンストラクタが含まれます。</p>
</div>

<pre class="brush: js">class CustomError extends Error {
  constructor(foo = 'bar', ...params) {
    // Pass remaining arguments (including vendor specific ones) to parent constructor
    super(...params);

    // Maintains proper stack trace for where our error was thrown (only available on V8)
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, CustomError);
    }

    this.name = 'CustomError';
    // Custom debugging information
    this.foo = foo;
    this.date = new Date();
  }
}

try {
  throw new CustomError('baz', 'bazMessage');
} catch(e){
  console.error(e.name); //CustomError
  console.error(e.foo); //baz
  console.error(e.message); //bazMessage
  console.error(e.stack); //stacktrace
}</pre>

<h4 id="ES5_Custom_Error_Object" name="ES5_Custom_Error_Object">ES5 独自のエラーオブジェクト</h4>

<div class="warning">
<p>prototype 宣言を使用した場合、<strong>すべて</strong>のブラウザーのスタックトレース上に、CustomError コンストラクタが含まれます。</p>
</div>

<pre class="brush: js">function CustomError(foo, message, fileName, lineNumber) {
  var instance = new Error(message, fileName, lineNumber);
  instance.name = 'CustomError';
  instance.foo = foo;
  Object.setPrototypeOf(instance, Object.getPrototypeOf(this));
  if (Error.captureStackTrace) {
    Error.captureStackTrace(instance, CustomError);
  }
  return instance;
}

CustomError.prototype = Object.create(Error.prototype, {
  constructor: {
    value: Error,
    enumerable: false,
    writable: true,
    configurable: true
  }
});

if (Object.setPrototypeOf){
  Object.setPrototypeOf(CustomError, Error);
} else {
  CustomError.__proto__ = Error;
}

try {
  throw new CustomError('baz', 'bazMessage');
} catch(e){
  console.error(e.name); //CustomError
  console.error(e.foo); //baz
  console.error(e.message); //bazMessage
}</pre>

<h2 id="Specifications" name="Specifications">仕様書</h2>

<table class="standard-table">
 <thead>
  <tr>
   <th scope="col">仕様書</th>
   <th scope="col">状態</th>
   <th scope="col">備考</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td>{{SpecName('ESDraft', '#sec-error-objects', 'Error')}}</td>
   <td>{{Spec2('ESDraft')}}</td>
   <td></td>
  </tr>
  <tr>
   <td>{{SpecName('ES2015', '#sec-error-objects', 'Error')}}</td>
   <td>{{Spec2('ES2015')}}</td>
   <td></td>
  </tr>
  <tr>
   <td>{{SpecName('ES5.1', '#sec-15.11', 'Error')}}</td>
   <td>{{Spec2('ES5.1')}}</td>
   <td></td>
  </tr>
  <tr>
   <td>{{SpecName('ES1')}}</td>
   <td>{{Spec2('ES1')}}</td>
   <td>初回定義。JavaScript 1.1 で実装。</td>
  </tr>
 </tbody>
</table>

<h2 id="Browser_compatibility" name="Browser_compatibility">ブラウザーの互換性</h2>

<div>
<div class="hidden">このページの互換性一覧表は構造化データから生成されています。データに協力していただけるのであれば、<a class="external" href="https://github.com/mdn/browser-compat-data">https://github.com/mdn/browser-compat-data</a> をチェックアウトしてプルリクエストを送信してください。</div>

<p>{{Compat("javascript.builtins.Error")}}</p>
</div>

<h2 id="See_also" name="See_also">関連情報</h2>

<ul>
 <li>{{jsxref("Error.prototype")}}</li>
 <li>{{jsxref("Statements/throw", "throw")}}</li>
 <li>{{jsxref("Statements/try...catch", "try...catch")}}</li>
</ul>