<div>{{jsSidebar("Statements")}}</div>

<p>La declaración <strong><code>try...catch</code></strong> señala un bloque de instrucciones a intentar (<strong><code>try</code></strong>), y especifica una respuesta si se produce una excepción (<strong><code>catch</code></strong>).</p>

<div>{{EmbedInteractiveExample("pages/js/statement-trycatch.html")}}</div>

<h2 id="Sintaxis" name="Sintaxis">Sintaxis</h2>

<pre class="syntaxbox">try {
   <em>try_statements</em>
}
[catch (<em>exception_var_1</em> if <em>condition_1</em>) { // non-standard
   <em>catch_statements_1</em>
}]
...
[catch (<em>exception_var_2</em>) {
   <em>catch_statements_2</em>
}]
[finally {
   <em>finally_statements</em>
}]
</pre>

<dl>
 <dt><code>try_statements</code></dt>
 <dd>Las sentencias que serán ejecutadas.</dd>
</dl>

<dl>
 <dt><code>catch_statements_1</code>, <code>catch_statements_2</code></dt>
 <dd>Sentencias que se ejecutan si una excepción es lanzada en el bloque <code>try</code>.</dd>
</dl>

<dl>
 <dt><code>exception_var_1</code>, <code>exception_var_2</code></dt>
 <dd>Identificador que contiene un objeto de excepcion asociado a la cláusula <code>catch</code>.</dd>
</dl>

<dl>
 <dt><code>condition_1</code></dt>
 <dd>Una expresión condicional.</dd>
</dl>

<dl>
 <dt><code>finally_statements</code></dt>
 <dd>Sentencias que se ejecutan después de que se completa la declaración <code>try</code> . Estas sentencias se ejecutan independientemente de si una excepcion fue lanzada o capturada.</dd>
</dl>

<h2 id="Descripci.C3.B3n" name="Descripci.C3.B3n">Descripción</h2>

<p>La declaración <code>try</code> consiste en un bloque <code>try</code> que contiene una o más sentencias (se debe usar siempre <code>{}</code> incluso para una sola sentencia) y al menos una cláusula <code>catch</code> o una cláusula <code>finally</code>, o bien ambas. Esto nos da tres formas posibles para la declaración <code>try</code>:</p>

<ol>
 <li><code>try...catch</code></li>
 <li><code>try...finally</code></li>
 <li><code>try...catch...finally</code></li>
</ol>

<p>Un bloque <code>catch</code> contiene sentencias que especifican que hacer si una excepción es lanzada en el bloque <code>try</code> . Es decir, usted quiere que el bloque <code>try</code> tenga éxito, pero si éste no lo tiene, usted quiere que el control pase al bloque <code>catch</code>. Si cualquier sentencia dentro del bloque <code>try</code> (o en una funcion llamada desde dentro del bloque <code>try</code>) lanza una excepción, el control cambia inmediatamente a la cláusula <code>catch</code> . Si ninguna excepcion es lanzada en el bloque <code>try</code> , la clausula <code>catch</code> se omite.</p>

<p>La cláusula <code>finally</code> se ejecuta despues del bloque <code>try</code>  y la(s) clausula(s) <code>catch</code> pero antes de las instrucciones que siguen a la declaración <code>try</code>. Ésta siempre se ejecuta, independientemente de si una excepción fue lanzada o capturada.</p>

<p>Puede anidar una o más sentencias <code>try</code>. Si una declaración <code>try</code> interna no tiene una cláusula <code>catch</code>, se ejecuta la cláusula <code>catch</code> de la declaración <code>try</code> que la encierra.</p>

<p>Usted también puede usar la declaración <code>try</code> para manejar excepciones de JavaScript. Consulte la <a href="https://developer.mozilla.org/es/docs/Web/JavaScript/Guide">Guía de JavaScript</a> para obtener mayor información sobre excepciones de JavaScript.<br>
  </p>

<h2 id="Unconditional_catch_clause" name="Unconditional_catch_clause">Cláusula incondicional <code>catch</code></h2>

<p>Cuando una única cláusula incondicional <code>catch</code> es usada, el bloque <code>catch</code> es ejecutado cuando cualquier excepción es lanzada. Por ejemplo, cuando la excepción ocurre en el siguiente código, el control se transfiere a la cláusula <code>catch</code>.</p>

<pre class="brush: js">try {
   throw "myException"; // genera una excepción
}
catch (e) {
   // sentencias para manejar cualquier excepción
   logMyErrors(e); // pasa el objeto de la excepción al manejador de errores
}
</pre>

<p>El bloque <code>catch</code> especifíca un identificador ( <code>e</code> en el ejemplo de arriba) que contiene el valor especificado por la sentencia <code>throw</code>. JavaScript crea este identificador cuando el bloque <code>catch</code> es ejecutado y lo agrega al ámbito actual; el identificador persiste solo durante la ejecución del bloque <code>catch</code>; después de que este términa de ejecutarse, el identificador ya no está disponible más.</p>

<h2 id="Conditional_catch_clauses" name="Conditional_catch_clauses">Cláusulas condicionales <code>catch</code></h2>

<p>{{non-standard_header}}</p>

<p>Usted también puede usar una o más cláusulas condicionales <code>catch</code> para manejar excepciones específicas. En este caso, la cláusula <code>catch</code> apropiada es ejecutada cuando la excepción específica es lanzada. En el siguiente ejemplo, el código en el bloque <code>try</code> puede potencialmente lanzar tres excepciones {{jsxref("TypeError")}}, {{jsxref("RangeError")}}, y {{jsxref("EvalError")}}. Cuando una excepción ocurre, el control se transfiere a la cláusula <code>catch</code> apropiada. Si la excepción no es una de las excepciones especificadas y una cláusula <code>catch</code> incondicional es encontrada, el control se transfiere a esa cláusula <code>catch</code>.</p>

<p>Si usted usa una cláusula <code>catch</code> incondicional con una o más cláusulas <code>catch</code> condicionales, la cláusula <code>catch</code> incondicional debe ser especificada al último. De otra forma, la cláusula <code>catch</code> incondicional interceptará todo tipo de excepciones antes de que puedan alcanzar las condicionales.</p>

<p>Recordatorio: ésta funcionalidad no es parte de la especificación ECMAScript y ha sido removida en Firefox 59. No es soportada en ningún navegador actuál.</p>

<pre class="brush: js">try {
   myroutine(); // puede lanzar tres tipos de excepciones
} catch (e if e instanceof TypeError) {
   // sentencias para manejar excepciones TypeError
} catch (e if e instanceof RangeError) {
   // sentencias para manejar excepciones RangeError
} catch (e if e instanceof EvalError) {
   // sentencias para manejar excepciones EvalError
} catch (e) {
   // sentencias para manejar cualquier excepción no especificada
   logMyErrors(e); // pasa el objeto de la excepción al manejador de errores
}
</pre>

<p>Y aquí está cómo implementar las mismas "Cláusulas <code>catch</code> condicionales" conforme a la especificación ECMAScript (obviamente es más verboso, pero funciona en cualquier parte):</p>

<pre class="brush: js line-numbers  language-js"><code class="language-js"><span class="keyword token">try</span> <span class="punctuation token">{</span>
    <span class="comment token">// puede lanzar tres tipos de excepciones</span>
    <span class="function token">myroutine</span><span class="punctuation token">(</span><span class="punctuation token">);<code class="language-js"><span class="comment token">  </span>
</code>}</span> <span class="keyword token">catch</span> <span class="punctuation token">(</span><span class="class-name token">e</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
    <span class="keyword token">if</span> <span class="punctuation token">(</span>e <span class="keyword token">instanceof</span> <span class="class-name token">TypeError</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
        <span class="comment token">// sentencias para manejar excepciones TypeError</span>
    <span class="punctuation token">}</span> <span class="keyword token">else</span> <span class="keyword token">if</span> <span class="punctuation token">(</span>e <span class="keyword token">instanceof</span> <span class="class-name token">RangeError</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
        <span class="comment token">// sentencias para manejar excepciones RangeError</span>
    <span class="punctuation token">}</span> <span class="keyword token">else</span> <span class="keyword token">if</span> <span class="punctuation token">(</span>e <span class="keyword token">instanceof</span> <span class="class-name token">EvalError</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
        <span class="comment token">// sentencias para manejar excepciones EvalError</span>
    <span class="punctuation token">}</span> <span class="keyword token">else</span> <span class="punctuation token">{</span>
       <span class="comment token">// sentencias para manejar cualquier excepción no especificada</span>
       <span class="function token">logMyErrors</span><span class="punctuation token">(</span>e<span class="punctuation token">)</span><span class="punctuation token">;</span> <span class="comment token">// </span><span class="punctuation token">pasa el objeto de la excepción al manejador de errores</span>
<span class="punctuation token">}</span></code></pre>

<h3 id="The_exception_identifier" name="The_exception_identifier">El identificador de excepciones</h3>

<p>Cuando una excepción es lanzada en el bloque <code>try</code>, <code><em>exception_var</em></code> (por ejemplo, la <code>e</code> en <code>catch (e)</code>) guarda el valor especificado por la sentencia <code>throw</code>. Usted puede usar éste identificador para obtener información acerca de la excepción que fue lanzada. Éste identificador es local a la cláusula <code>catch</code>. Esto significa que, es creado cuando la cláusula <code>catch</code> es ejecutada, y después de que termine de ejecutarse, el identificador no estará disponible más.</p>

<h3 id="The_finally_clause" name="The_finally_clause">La cláusula <code>finally</code></h3>

<p>La cláusula <code>finally</code> contiene sentencias a ejecutarse después de que las cláusulas <code>try</code> y <code>catch</code> se ejecuten, pero antes de las sentencias que le siguen al bloque <code>try..catch..finally</code>. Note que la cláusula <code>finally</code> se ejecuta sin importar si una excepción es o no lanzada. Si una excepción es lanzada, las instrucciones en la cláusula <code>finally</code> se ejecutan incluso si ninguna cláusula <code>catch</code> maneja la excepción.</p>

<p>Usted puede usar la cláusula finally para hacer que su script falle plácidamente cuando una excepción ocurra; por ejemplo, para hacer una limpieza general, usted puede necesitar liberar un recurso que su script haya retenido.</p>

<p>Puede parecer extraño tener una cláusula relacionada a una excepción que se ejecuta sin importar si hay una excepción o no, pero esta concepción en realidad sirve a un propósito. El punto importante no es que la cláusula <code>finally</code> siempre se ejecuta, si no más bien que el codigo ordinario que le sigue a <code>try..catch</code> no.</p>

<p>Por ejemplo, si otra excepción ocurre dentro de un bloque <code>catch</code> de una declaración <code>try</code>, cualquier codigo restante en el mismo bloque exterior <code>try</code> que encierra ese <code>try..catch</code> (o en el flujo principal, si no es un bloque <code>try</code> exterior) , no será ejecutado, dado que el control es inmediatamente transferido al bloque <code>catch</code> del <code>try</code> exterior (o el generador de error interno, si no es en un bloque <code>try</code>).</p>

<p>Por lo tanto, cualquier rutina de limpieza hecha en esa sección encerrada (o la principal) antes de que exista, será saltada. Sin embargo, si la declaración <code>try</code> tiene un bloque <code>finally</code>, entonces el código de ese bloque <code>finally</code> será ejecutado primero para permitir tal limpieza, y ENTONCES el bloque <code>catch</code> de la otra declaración <code>try</code> (o el generador de error) tomará el control para manejar la segunda excepción.</p>

<p>Ahora, si esa rutina de limpieza debiera ser hecha ya sea que el código del <code>try..catch</code> tenga éxito o no, entonces si el bloque <code>finally</code> se ejecutase solo después de una excepción, el mismo código de limpieza tendría que estar presente dentro y fuera del bloque <code>finally</code>, y por lo tanto no hay razón para no tener el bloque <code>finally</code> solo, y dejarlo ejecutarse sin importar si hay excepciones o no.</p>

<p>El siguiente ejemplo abre un archivo y despues ejecuta sentencias que usan el archivo (JavaScript del lado del servidor permite acceder a archivos). Si una excepción es lanzada mientras el archivo está abierto, la cláusula <code>finally</code> cierra el archivo antes de que el script falle. El código en <code>finally</code> también se ejecuta después de un retorno explícito de los bloques <code>try</code> o <code>catch</code>.</p>

<pre class="brush: js">openMyFile()
try {
   // retiene un recurso
   writeMyFile(theData);
}
finally {
   closeMyFile(); // siempre cierra el recurso
}
</pre>

<h2 id="Ejemplos" name="Ejemplos">Ejemplos</h2>

<h3 id="The_finally_clause" name="The_finally_clause">Bloques try anidados</h3>

<p>Primero, veamos que pasa con esto:</p>

<pre class="brush: js line-numbers  language-js"><code class="language-js"><span class="keyword token">try</span> <span class="punctuation token">{</span>
  <span class="keyword token">try</span> <span class="punctuation token">{</span>
    <span class="keyword token">throw</span> <span class="keyword token">new</span> <span class="class-name token">Error</span><span class="punctuation token">(</span><span class="string token">'oops'</span><span class="punctuation token">)</span><span class="punctuation token">;</span>
  <span class="punctuation token">}</span>
  <span class="keyword token">finally</span> <span class="punctuation token">{</span>
    console<span class="punctuation token">.</span><span class="function token">log</span><span class="punctuation token">(</span><span class="string token">'finally'</span><span class="punctuation token">)</span><span class="punctuation token">;</span>
  <span class="punctuation token">}</span>
<span class="punctuation token">}</span>
<span class="keyword token">catch</span> <span class="punctuation token">(</span><span class="class-name token">ex</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
  console<span class="punctuation token">.</span><span class="function token">error</span><span class="punctuation token">(</span><span class="string token">'outer'</span><span class="punctuation token">,</span> ex<span class="punctuation token">.</span>message<span class="punctuation token">)</span><span class="punctuation token">;</span>
<span class="punctuation token">}</span>

<span class="comment token">// Output:</span>
<span class="comment token">// "finally"</span>
<span class="comment token">// "outer" "oops"</span></code></pre>

<p>Ahora, si nosotros ya capturamos la excepción en una declaración try interna agregando un bloque catch.</p>

<pre class="brush: js line-numbers  language-js"><code class="language-js"><span class="keyword token">try</span> <span class="punctuation token">{</span>
  <span class="keyword token">try</span> <span class="punctuation token">{</span>
    <span class="keyword token">throw</span> <span class="keyword token">new</span> <span class="class-name token">Error</span><span class="punctuation token">(</span><span class="string token">'oops'</span><span class="punctuation token">)</span><span class="punctuation token">;</span>
  <span class="punctuation token">}</span>
  <span class="keyword token">catch</span> <span class="punctuation token">(</span><span class="class-name token">ex</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
    console<span class="punctuation token">.</span><span class="function token">error</span><span class="punctuation token">(</span><span class="string token">'inner'</span><span class="punctuation token">,</span> ex<span class="punctuation token">.</span>message<span class="punctuation token">)</span><span class="punctuation token">;</span>
  <span class="punctuation token">}</span>
  <span class="keyword token">finally</span> <span class="punctuation token">{</span>
    console<span class="punctuation token">.</span><span class="function token">log</span><span class="punctuation token">(</span><span class="string token">'finally'</span><span class="punctuation token">)</span><span class="punctuation token">;</span>
  <span class="punctuation token">}</span>
<span class="punctuation token">}</span>
<span class="keyword token">catch</span> <span class="punctuation token">(</span><span class="class-name token">ex</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
  console<span class="punctuation token">.</span><span class="function token">error</span><span class="punctuation token">(</span><span class="string token">'outer'</span><span class="punctuation token">,</span> ex<span class="punctuation token">.</span>message<span class="punctuation token">)</span><span class="punctuation token">;</span>
<span class="punctuation token">}</span>

<span class="comment token">// Output:</span>
<span class="comment token">// "inner" "oops"</span>
<span class="comment token">// "finally"</span></code></pre>

<p>Y ahora vamos a relanzar el error.</p>

<pre class="brush: js line-numbers  language-js"><code class="language-js"><span class="keyword token">try</span> <span class="punctuation token">{</span>
  <span class="keyword token">try</span> <span class="punctuation token">{</span>
    <span class="keyword token">throw</span> <span class="keyword token">new</span> <span class="class-name token">Error</span><span class="punctuation token">(</span><span class="string token">'oops'</span><span class="punctuation token">)</span><span class="punctuation token">;</span>
  <span class="punctuation token">}</span>
  <span class="keyword token">catch</span> <span class="punctuation token">(</span><span class="class-name token">ex</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
    console<span class="punctuation token">.</span><span class="function token">error</span><span class="punctuation token">(</span><span class="string token">'inner'</span><span class="punctuation token">,</span> ex<span class="punctuation token">.</span>message<span class="punctuation token">)</span><span class="punctuation token">;</span>
    <span class="keyword token">throw</span> ex<span class="punctuation token">;</span>
  <span class="punctuation token">}</span>
  <span class="keyword token">finally</span> <span class="punctuation token">{</span>
    console<span class="punctuation token">.</span><span class="function token">log</span><span class="punctuation token">(</span><span class="string token">'finally'</span><span class="punctuation token">)</span><span class="punctuation token">;</span>
  <span class="punctuation token">}</span>
<span class="punctuation token">}</span>
<span class="keyword token">catch</span> <span class="punctuation token">(</span><span class="class-name token">ex</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
  console<span class="punctuation token">.</span><span class="function token">error</span><span class="punctuation token">(</span><span class="string token">'outer'</span><span class="punctuation token">,</span> ex<span class="punctuation token">.</span>message<span class="punctuation token">)</span><span class="punctuation token">;</span>
<span class="punctuation token">}</span>

<span class="comment token">// Output:</span>
<span class="comment token">// "inner" "oops"</span>
<span class="comment token">// "finally"</span>
<span class="comment token">// "outer" "oops"</span></code></pre>

<p>Cualquier excepción dad será capturada solo una vez por el bloque catch más cercano a menos que sea relanzado. Por supuesto cualquier nueva excepción que se origine en el bloque 'interno' (porque el código en el bloque catch puede hacer algo que lanze un error), será capturado por el bloque 'externo'.</p>

<h3 id="Retornando_de_un_bloque_finally">Retornando de un bloque finally</h3>

<p>Si el bloque <code>finally</code> retorna un valor, este valor se convierte en el valor de retorno de toda la producción <code>try-catch-finally</code>, a pesar de cualquier sentencia <code>return</code> en los bloques <code>try</code> y <code>catch</code>. Esto incluye excepciones lanzadas dentro del bloque catch.</p>

<pre class="brush: js line-numbers  language-js"><code class="language-js"><span class="punctuation token">(</span><span class="keyword token">function</span><span class="punctuation token">(</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
  <span class="keyword token">try</span> <span class="punctuation token">{</span>
    <span class="keyword token">try</span> <span class="punctuation token">{</span>
      <span class="keyword token">throw</span> <span class="keyword token">new</span> <span class="class-name token">Error</span><span class="punctuation token">(</span><span class="string token">'oops'</span><span class="punctuation token">)</span><span class="punctuation token">;</span>
    <span class="punctuation token">}</span>
    <span class="keyword token">catch</span> <span class="punctuation token">(</span><span class="class-name token">ex</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
      console<span class="punctuation token">.</span><span class="function token">error</span><span class="punctuation token">(</span><span class="string token">'inner'</span><span class="punctuation token">,</span> ex<span class="punctuation token">.</span>message<span class="punctuation token">)</span><span class="punctuation token">;</span>
      <span class="keyword token">throw</span> ex<span class="punctuation token">;</span>
    <span class="punctuation token">}</span>
    <span class="keyword token">finally</span> <span class="punctuation token">{</span>
      console<span class="punctuation token">.</span><span class="function token">log</span><span class="punctuation token">(</span><span class="string token">'finally'</span><span class="punctuation token">)</span><span class="punctuation token">;</span>
      <span class="keyword token">return</span><span class="punctuation token">;</span>
    <span class="punctuation token">}</span>
  <span class="punctuation token">}</span>
  <span class="keyword token">catch</span> <span class="punctuation token">(</span><span class="class-name token">ex</span><span class="punctuation token">)</span> <span class="punctuation token">{</span>
    console<span class="punctuation token">.</span><span class="function token">error</span><span class="punctuation token">(</span><span class="string token">'outer'</span><span class="punctuation token">,</span> ex<span class="punctuation token">.</span>message<span class="punctuation token">)</span><span class="punctuation token">;</span>
  <span class="punctuation token">}</span>
<span class="punctuation token">}</span><span class="punctuation token">)</span><span class="punctuation token">(</span><span class="punctuation token">)</span><span class="punctuation token">;</span>

<span class="comment token">// Output:</span>
<span class="comment token">// "inner" "oops"</span>
<span class="comment token">// "finally"</span></code></pre>

<p>El "oops" externo no es lanzado debido al retorno en el bloque finally. Lo mismo aplicaría para cualquier valor retornado del bloque catch.</p>

<p>Vea los ejemplos para {{jsxref("Sentencias/throw", "throw")}}.</p>

<h2 id="Vea_Tambi.C3.A9n" name="Vea_Tambi.C3.A9n">Vea también</h2>

<ul>
 <li>{{jsxref("Error")}}</li>
 <li>{{jsxref("Sentencias/throw", "throw")}}</li>
</ul>